name: learn-github-actions
run-name: ${{ github.actor }} is learning GitHub Actions
on: [push]
jobs:
  check-bats-version:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v3
        with:
          node-version: '14'
      - run: npm install -g bats
      - run: bats -v
      
  create-zip-archive:
     runs-on: ubuntu-latest
     steps: 
      - name: checkout code
        uses: actions/checkout@v2
      - name: create zip archive
        run:
          zip -r sample2.zip sample2
      - name: upload zip artifact
        uses: actions/upload-artifact@v2
        with:
          name: sample2-artifact
          path: sample2.zip
        
    
